SELECT j.ID, j.NAME
FROM (SELECT p.ID, p.NAME
FROM PLACES as p
JOIN SCHEDULES as s
on p.ID = s.PLACE_ID
WHERE DATE(SCHEDULED_AT) = '2019-01-06 00:00:00') as j
WHERE j.id in (SELECT PLACE_ID FROM PLACE_REVIEWS)